package dev.status.web;

import dev.status.dto.ServiceHistory;
import dev.status.dto.ServiceList;
import dev.status.dto.ServiceStatus;
import org.mapstruct.Mapper;

/**
 * Boundary mapper: application-service result types → wire response DTOs.
 * Generated by MapStruct (componentModel = "spring") as a Spring bean that the
 * controller injects by constructor. The controller never returns the service's
 * own types or JPA entities.
 *
 * <p>Field names, null handling (nullable description/team/statusChangedAt/
 * latencyMs/lastCheckedAt pass through as null), and JSON shape match the
 * wire contract exactly — {@code ContractGoldenTest} pins the result.</p>
 */
@Mapper(componentModel = "spring")
public interface ServiceResponseMapper {

    ServiceStatusResponse toResponse(ServiceStatus status);

    ServiceListResponse toResponse(ServiceList list);

    StatusHistoryResponse toResponse(ServiceHistory history);
}
